// Code generated by "stringer -type=Capability"; DO NOT EDIT.

package models

import "strconv"

const _Capability_name = "CapSuperAdminCapUserAdminCapIDMax"

var _Capability_index = [...]uint8{0, 13, 25, 33}

func (i Capability) String() string {
	if i < 0 || i >= Capability(len(_Capability_index)-1) {
		return "Capability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Capability_name[_Capability_index[i]:_Capability_index[i+1]]
}
